INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');
INSERT INTO id (`type`) VALUES ('volunteer');

INSERT INTO volunteers
VALUES (FALSE,FALSE,1,'password', 'bob', 'barker', '123 Baker St','Calgary','AB','A1A 1A1','555-555-5566','555-555-5599','bobbarker@price.com','10-10-1997','Male','L','I like animals','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,false,false');

INSERT INTO volunteers
VALUES (FALSE,FALSE,2,'password', 'keith', 'baker', '123 Fake St','Calgary','AB','A1A 1A2','555-555-5566','555-555-5599','keith@mail.com','10-10-1990','Male','XL','This is a sentence','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,false,false');

INSERT INTO volunteers
VALUES (FALSE,FALSE,3,'password', 'suzy', 'smith', '345 That Lane','Calgary','AB','A1A 2A2','555-555-5566','555-555-5599','suzy@mail.com','10-10-1990','Female','M','I want to help animals','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,false,false');

INSERT INTO volunteers
VALUES (FALSE,FALSE,4,'password', 'james', 'horner', '678 This Lane','Calgary','AB','A1A 3B2','555-555-5566','555-555-5599','james@mail.com','10-10-1990','Male','L','Esms ms a seneence','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,false,false');

INSERT INTO volunteers
VALUES (FALSE,FALSE,5,'password', 'max', 'jones', '99 Place Place','Calgary','AB','A1A 5F4','555-555-5566','555-555-5599','max@mail.com','10-10-1990','Male','L','xs xs a senence','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,false,false');

INSERT INTO volunteers
VALUES (FALSE,FALSE,6,'password', 'david', 'lee', '66 Street Street','Calgary','AB','F1S 1A1','555-555-5566','555-555-5599','david@mail.com','10-10-1997','Male','L','Idvs vs a senience','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,false,false');

INSERT INTO volunteers
VALUES (FALSE,FALSE,7,'password', 'jack', 'parker', '345 Baker St','Calgary','AB','B7C 1A1','555-555-5566','555-555-5599','jack@mail.com','10-10-1992','Male','L','Kcs cs a senkence','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,false,false');

INSERT INTO volunteers
VALUES (FALSE,FALSE,8,'password', 'arin', 'hanson', '125 Hill St','Calgary','AB','T2A 1A1','555-555-5566','555-555-5599','arin@mail.com','10-10-1992','Male','L','Nis is a sennence','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,false,false');

INSERT INTO volunteers
VALUES (FALSE,FALSE,9,'password', 'samantha', 'miller', '123 Valley Dr','Calgary','AB','H2A 5FS','555-555-5566','555-555-5599','sam@mail.com','10-10-1992','Female','S','I wley lo errlp lmals','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,false,false');

INSERT INTO volunteers
VALUES (FALSE,FALSE,10,'password', 'susan', 'davis', '1809 Tree Lane','Calgary','AB','A1A 7J7','555-555-5566','555-555-5599','susan@mail.com','10-10-1992','Female','S','I waee io snelp avmals','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,false,false');

INSERT INTO volunteers
VALUES (FALSE,FALSE,11,'password', 'jill', 'johnson', '6752 Lake Dr','Calgary','AB','A1A 9K9','555-555-5566','555-555-5599','jill@mail.com','10-10-1997','Female','M','I wrke no sonlp rhmals','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,true,true');

INSERT INTO volunteers
VALUES (FALSE,FALSE,12,'password', 'jeff', 'williams', '112 Mountain Rd','Calgary','AB','A1A 9L8','555-555-5566','555-555-5599','jeff@mail.com','10-10-1985','Male','M','Ffs fs a enfence','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,true,true');

INSERT INTO volunteers
VALUES (FALSE,FALSE,13,'password', 'mike', 'tayler', '102 Forest Ave','Calgary','AB','A1A 6J5','555-555-5566','555-555-5599','mike@mail.com','10-10-1985','Male','M','Eks ks a eneence','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,true,true');

INSERT INTO volunteers
VALUES (FALSE,FALSE,14,'password', 'bill', 'anderson', '19373 That St','Calgary','AB','A1A 6S3','555-555-5566','555-555-5599','bill@mail.com','10-10-1985','Male','M','Lls ls a enlence','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,true,true');

INSERT INTO volunteers
VALUES (FALSE,FALSE,15,'password', 'robert', 'moore', '101 River Dr','Calgary','AB','A1A 6M2','555-555-5566','555-555-5599','robert@mail.com','10-10-1997','Male','L','Ertbs bs a eneence','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,true,true');

INSERT INTO volunteers
VALUES (FALSE,FALSE,16,'password', 'fred', 'jackson', '1245 Rock Ave','Calgary','AB','A1A 7N2','555-555-5566','555-555-5599','fred@mail.com','10-10-1999','Male','XL','Des es a endence','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,true,true');

INSERT INTO volunteers
VALUES (FALSE,FALSE,17,'password', 'frank', 'white', '192 Jackson Way','Calgary','AB','A1A 4N9','555-555-5566','555-555-5599','frank@mail.com','10-10-1999','Male','L','Nkas as a ennence','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,true,true');

INSERT INTO volunteers
VALUES (FALSE,FALSE,18,'password', 'kelly', 'thompson', '1861 Beach Dr','Calgary','AB','A1A 9M2','555-555-5566','555-555-5599','kelly@mail.com','10-10-1999','Female','L','I wach mo psonrlp omals','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,true,true');

INSERT INTO volunteers
VALUES (FALSE,FALSE,19,'password', 'alex', 'wilson', '1604 Desert Lane','Calgary','AB','A1A 3D3','555-555-5566','555-555-5599','alex@mail.com','10-10-1987','Male','S','Xes es a enxence','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,true,true');

INSERT INTO volunteers
VALUES (FALSE,FALSE,20,'password', 'ivan', 'walker', '156 Creek Ave','Calgary','AB','A1A 7J5','555-555-5566','555-555-5599','ivan@mail.com','10-10-1986','Male','L','Nas as a ennence','Tiffany','Erikson','Friend','444-444-5679','444-444-1235','tiffany@emergency.ca','Izzy','Jenkins','Co-worker','444-444-5678','444-444-1234','izzy@emergency.ca','Greg','Gonzalaz','555-555-1235','greg@reference.ca','Carlos','Gonzalaz','555-555-1234','carlos@reference.ca',TRUE,'true,true,true,true');



INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');
INSERT INTO id (`type`) VALUES ('foster');

INSERT INTO fosters
VALUES (FALSE,FALSE,21,'password','bilaal','joyce', '123 Baker St','Calgary','AB','A1A 1A1','555-555-5566','555-555-5599',TRUE,'demons@email.com','House',TRUE,NULL,FALSE,'Bilaal Joyce 20; Kim Joyce 22',TRUE,TRUE,TRUE,'If yes, please list all pets details and are they good with new animals?','If you have animals, are they spayed/neutered and up to date on all vaccines?','no dogs','no cats',TRUE,'true true true true true true','Describe the type of animal you would like to foster and we will try to match your request',TRUE,TRUE,'10',TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,3,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,22,'password','george', 'horner', '123 Fake St','Calgary','AB','A1A 1A2','555-555-5566','555-555-5599',TRUE,'george@mail.com','House',TRUE,NULL,FALSE,'25; 22',FALSE,TRUE,TRUE,'this is a sentence','sentence','combination','indoor',TRUE,'true true true true true true','Words and stuff',FALSE,TRUE,'60',TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,2,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,23,'password','harvey', 'jones', '345 That Lane','Calgary','AB','A1A 2A2','555-555-5566','555-555-5599',TRUE,'harvey@mail.com','House',TRUE,NULL,FALSE,'25, 23',FALSE,TRUE,TRUE,'this is a sentence','words','indoor','outdoor',TRUE,'true true true true true true','Animals',FALSE,TRUE,'50',TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,5,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,24,'password','lewis', 'lee', '678 This Lane','Calgary','AB','A1A 3B2','555-555-5566','555-555-5599',TRUE,'lewis@mail.com','House',FALSE,'Mr. Landlord 403-555-5555',FALSE,'20; 26',FALSE,TRUE,TRUE,'this is a sentence','this is a sentence','outdoor','combination',FALSE,'true true true true true true','Something',FALSE,TRUE,'70',FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,6,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,25,'password','simon', 'parker', '99 Place Place','Calgary','AB','A1A 5F4','555-555-5566','555-555-5599',TRUE,'simon@mail.com','House',FALSE,'Mr. Landlord 403-555-5555',FALSE,'28; 29',FALSE,TRUE,FALSE,NULL,'this is a sentence','no dogs','no cats',TRUE,'true true true true true true','Description',FALSE,TRUE,'60',FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE,4,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,26,'password','chris', 'hanson', '66 Street Street','Calgary','AB','F1S 1A1','555-555-5566','555-555-5599',TRUE,'chris@mail.com','Duplex',FALSE,'Mr. Landlord 403-555-5555',FALSE,'25; 26; 30',FALSE,FALSE,FALSE,NULL,'Idvs vs a senience','combination','indoor',TRUE,'true true true true true true','this is a sentence',FALSE,TRUE,'10',FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,TRUE,3,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,27,'password','david', 'miller', '345 Baker St','Calgary','AB','B7C 1A1','555-555-5566','555-555-5599',TRUE,'david','Duplex',FALSE,'Mr. Landlord 403-555-5555',FALSE,'28',FALSE,FALSE,FALSE,NULL,'Kcs cs a senkence','indoor','outdoor',TRUE,'true true true true true true','Idvs vs a senience',FALSE,FALSE,0,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,TRUE,2,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,28,'password','alexander', 'davis', '125 Hill St','Calgary','AB','T2A 1A1','555-555-5566','555-555-5599',TRUE,'alexande@mail.com','Duplex',FALSE,'Mr. Landlord 403-555-5555',FALSE,'26; 29',FALSE,FALSE,FALSE,NULL,'Nis is a sennence','outdoor','combination',TRUE,'true true true true true true','Kcs cs a senkence',FALSE,FALSE,0,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,TRUE,6,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,29,'password','albert', 'johnson', '123 Valley Dr','Calgary','AB','H2A 5FS','555-555-5566','555-555-5599',TRUE,'albert@mail.com','Duplex',FALSE,'Mr. Landlord 403-555-5555',FALSE,'25; 26; 40',FALSE,FALSE,FALSE,NULL,'I wley lo errlp lmals','no dogs','no cats',FALSE,'true true true true true true','Nis is a sennence',TRUE,FALSE,0,TRUE,FALSE,FALSE,TRUE,TRUE,FALSE,TRUE,2,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,30,'password','harry', 'williams', '1809 Tree Lane','Calgary','AB','A1A 7J7','555-555-5566','555-555-5599',TRUE,'harry@mail.com','Duplex',FALSE,'Mr. Landlord 403-555-5555',FALSE,'21; 29',FALSE,FALSE,FALSE,NULL,'I waee io snelp avmals','combination','indoor',FALSE,'true true true true true true','I wley lo errlp lmals',TRUE,FALSE,0,TRUE,FALSE,FALSE,TRUE,TRUE,FALSE,TRUE,1,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,31,'password','jim', 'tayler', '6752 Lake Dr','Calgary','AB','A1A 9K9','555-555-5566','555-555-5599',TRUE,'jim@mail.com','Apartment',FALSE,'Mr. Landlord 403-555-5555',TRUE,'10; 32; 34',FALSE,FALSE,FALSE,NULL,'I wrke no sonlp rhmals','indoor','outdoor',FALSE,'true true true true true true','I waee io snelp avmals',TRUE,TRUE,'1',TRUE,FALSE,FALSE,TRUE,TRUE,FALSE,TRUE,1,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,32,'password','dwight', 'anderson', '112 Mountain Rd','Calgary','AB','A1A 9L8','555-555-5566','555-555-5599',TRUE,'dwight@mail.com','Apartment',FALSE,'Mr. Landlord 403-555-5555',TRUE,'10; 15; 35; 34',FALSE,FALSE,FALSE,NULL,'Ffs fs a enfence','outdoor','combination',FALSE,'true true true true true true','I wrke no sonlp rhmals',TRUE,TRUE,'45',TRUE,FALSE,FALSE,TRUE,FALSE,TRUE,FALSE,1,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,33,'password','pamela', 'moore', '102 Forest Ave','Calgary','AB','A1A 6J5','555-555-5566','555-555-5599',TRUE,'pamela@mail.com','Apartment',TRUE,NULL,TRUE,'12; 29; 30',TRUE,FALSE,FALSE,NULL,'Eks ks a eneence','no dogs','no cats',TRUE,'true true true true true true','Ffs fs a enfence',TRUE,TRUE,'55',FALSE,FALSE,FALSE,TRUE,FALSE,TRUE,FALSE,2,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,34,'password','scott', 'jackson', '19373 That St','Calgary','AB','A1A 6S3','555-555-5566','555-555-5599',TRUE,'scott@mail.com','Mobile Home',TRUE,NULL,TRUE,'5; 28; 30',TRUE,FALSE,TRUE,'this is a sentence','Lls ls a enlence','combination','indoor',TRUE,'true true true true true true','Eks ks a eneence',TRUE,TRUE,'30',FALSE,FALSE,FALSE,TRUE,FALSE,TRUE,FALSE,4,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,35,'password','jimmy', 'white', '101 River Dr','Calgary','AB','A1A 6M2','555-555-5566','555-555-5599',TRUE,'jimmy@mail.com','Mobile Home',TRUE,NULL,TRUE,'7; 32; 29',TRUE,FALSE,TRUE,'this is a sentence','Ertbs bs a eneence','indoor','outdoor',TRUE,'true true true true true true','Lls ls a enlence',FALSE,FALSE,0,FALSE,FALSE,FALSE,TRUE,FALSE,TRUE,FALSE,24,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,36,'password','catherine', 'thompson', '1245 Rock Ave','Calgary','AB','A1A 7N2','555-555-5566','555-555-5599',TRUE,'catherine@mail.com','Farm/Acreage',TRUE,NULL,TRUE,'17; 35',TRUE,TRUE,TRUE,'this is a sentence','Des es a endence','outdoor','combination',TRUE,'true true true true true true','Ertbs bs a eneence',FALSE,FALSE,0,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,FALSE,7,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,37,'password','peter','johnston', '192 Jackson Way','Calgary','AB','A1A 4N9','555-555-5566','555-555-5599',TRUE,'peter@mail.com','Farm/Acreage',FALSE,'Mr. Landlord 403-555-5555',TRUE,'16; 37; 38',FALSE,TRUE,TRUE,'this is a sentence','Nkas as a ennence','no dogs','no cats',TRUE,'true true true true true true','Des es a endence',FALSE,FALSE,0,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,FALSE,5,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,38,'password','lisa','grayson', '1861 Beach Dr','Calgary','AB','A1A 9M2','555-555-5566','555-555-5599',TRUE,'lisa@mail.com','Basement Suite',FALSE,'Mr. Landlord 403-555-5555',TRUE,'13; 32; 32',FALSE,TRUE,TRUE,'this is a sentence','I wach mo psonrlp omals','combination','indoor',FALSE,'true true true true true true','Nkas as a ennence',FALSE,FALSE,0,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,4,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,39,'password','matt','skywalker', '1604 Desert Lane','Calgary','AB','A1A 3D3','555-555-5566','555-555-5599',TRUE,'matt@mail.com','Basement Suite',FALSE,'Mr. Landlord 403-555-5555',TRUE,'11; 32; 31',FALSE,TRUE,TRUE,'this is a sentence','Xes es a enxence','indoor','outdoor',TRUE,'true true true true true true','I wach mo psonrlp omals',TRUE,TRUE,'40',TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,3,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);

INSERT INTO fosters
VALUES (FALSE,FALSE,40,'password','jimbo','carry', '156 Creek Ave','Calgary','AB','A1A 7J5','555-555-5566','555-555-5599',TRUE,'jimbo@mail.com','Basement Suite',TRUE,NULL,TRUE,'10; 7; 15; 36; 37',TRUE,TRUE,TRUE,'this is a sentence','I awds akrmt','outdoor','combination',TRUE,'true true true true true true','Xes es a enxence',TRUE,TRUE,'60',TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,2,'James','Davidson','444-444-1234','davidson@reference.ca','Janet','Davidson','444-444-1237','janet@reference.ca','Phillip','Davidson','444-444-1239','phillip@reference.ca',TRUE);



INSERT INTO catapplication (nameofcat,fname,lname,address,city,province,postalcode,homephone,cellphone,email,age,personcatisfor,householdagreement,membersintroduced,catallergies,howmanyadults,howmanychild,childrenages,childrenhandling,childrenvisit,visitingfrequency,childrenprepared,familybusy,activefamily,scheduleregularity,familypersonality,plans,typeofresidence,own,landlordcontact,catsallowed,restrictions,outdoorareas,busystreet,cathome,livingsituationchanges,anycats,catsinfo,catattitude,otherpets,otherpetsinfo,spayedandneutered,animallocation,prioradoption,groupname,surrenderedanimal,circumstances,vetinfo,expectations,mainpurpose,primarycaretaker,catsprior,vacationhome,leftaloneweekday,leftaloneweekend,dailyexercise,petadjustment,foodexpenses,vetexpenses,groomingexpenses,boardingexpenses,gender,catcoat,catage,breedtypecolour,friendlywithchild,friendlywithdogs,friendlywithcats,friendlywithme,friendlywithvisitors,enjoybeinggroomed,enjoybeingheld,enjoybeingpetted,becalm,beactive,beplayful,bequiet,beindependant,wakeupatnight,aggressivebehaviour,beprotective,littertrained,declawed,firsttimeowner,handledifficultcat,medicalhandling,kittenmedical,nailcare,behaviouralissues,declawcat,catpast,catinsurance,giveupcat,catcirucumstances,additionalinformation,ref1fname,ref1lname,ref1relationship,ref1phonenumber,ref1email,ref2fname,ref2lname,ref2relationship,ref2phonenumber,ref2email,findoutanimal)
VALUES ('Tigger','Xander','Davis','123 Rainbow ST','Calgary','AB','A1A 1A1','123-456-7890',123-456-7890,'alexander.davis@edu.sait.ca',22,'Myself',TRUE,TRUE,FALSE,2,2,'19,22','Somewhat Capable',FALSE,'Never','Understand the limits of a cat','Somewhat','Regular','Calm','No change','Home','Home',TRUE,NULL,TRUE,'Outdoor cat room','Not busy','Free Roam','sagasjlghaslgsahgahsgudlshgjsalghajslghaslkgsdshjkl','dgasfgsgfdshajhdahguislghajgjsa;gdhalg',FALSE,'Diabetic cat','No Preference',TRUE,'Bird: Yells a lot and is annoying',1,'Home in downtown',TRUE,'SPCA',TRUE,'asglhdajlghdasjlghasjkgldsahgjskg','Outgoing and fun','Emotional help','Myself',TRUE,TRUE,'Tabby',3,1,1,1,10000,11000,12000,13000,TRUE,TRUE, 'kitten','S','N','V','S','V','V','V','S','S','S','S','V','N','S','N','N','N','N','N','Y','Y',TRUE,TRUE,'Salon','Any and all are fine',FALSE,'agdasgsagdasgasgsagsdgasddgagdas',FALSE,FALSE,'djfshfgfldsjghfdslg','dfhflhfdusagsauigidhsaguishguihsgsf','Jack','Daniels','Friend','098-765-4321','yes@yes.ca','Isabella','Goldshire','Friend','444-333-2222','animal@lover.ca','PetSmart');

INSERT INTO catapplication (nameofcat,fname,lname,address,city,province,postalcode,homephone,cellphone,email,age,personcatisfor,householdagreement,membersintroduced,catallergies,howmanyadults,howmanychild,childrenages,childrenhandling,childrenvisit,visitingfrequency,childrenprepared,familybusy,activefamily,scheduleregularity,familypersonality,plans,typeofresidence,own,landlordcontact,catsallowed,restrictions,outdoorareas,busystreet,cathome,livingsituationchanges,anycats,catsinfo,catattitude,otherpets,otherpetsinfo,spayedandneutered,animallocation,prioradoption,groupname,surrenderedanimal,circumstances,vetinfo,expectations,mainpurpose,primarycaretaker,catsprior,vacationhome,leftaloneweekday,leftaloneweekend,dailyexercise,petadjustment,foodexpenses,vetexpenses,groomingexpenses,boardingexpenses,gender,catcoat,catage,breedtypecolour,friendlywithchild,friendlywithdogs,friendlywithcats,friendlywithme,friendlywithvisitors,enjoybeinggroomed,enjoybeingheld,enjoybeingpetted,becalm,beactive,beplayful,bequiet,beindependant,wakeupatnight,aggressivebehaviour,beprotective,littertrained,declawed,firsttimeowner,handledifficultcat,medicalhandling,kittenmedical,nailcare,behaviouralissues,declawcat,catpast,catinsurance,giveupcat,catcirucumstances,additionalinformation,ref1fname,ref1lname,ref1relationship,ref1phonenumber,ref1email,ref2fname,ref2lname,ref2relationship,ref2phonenumber,ref2email,findoutanimal)
VALUES ('Sir fuffy beans','Tiernan','Nolan','123 Rainbow ST','Calgary','AB','B1B 1B1','123-456-7890',123-456-7890,'Tiernan@nolan.ca',37,'Daughter',TRUE,TRUE,FALSE,2,2,'37,40','Somewhat Capable',FALSE,'Never','Understand the limits of a cat','Somewhat','Regular','Calm','No change','Home','Home',TRUE,NULL,TRUE,'Outdoor cat room','Not busy','Free Roam','sagasjlghaslgsahgahsgudlshgjsalghajslghaslkgsdshjkl','dgasfgsgfdshajhdahguislghajgjsa;gdhalg',FALSE,'Diabetic cat','No Preference',TRUE,'Bird: Yells a lot and is annoying',1,'Home in downtown',TRUE,'SPCA',TRUE,'asglhdajlghdasjlghasjkgldsahgjskg','Outgoing and fun','Emotional help','Myself',TRUE,TRUE,'Tabby',3,1,1,1,10000,11000,12000,13000,TRUE,TRUE,'senior','S','N','V','S','V','V','V','S','S','S','S','V','N','S','N','N','N','N','N','Y','Y',TRUE,TRUE,'Salon','Any and all are fine',FALSE,'agdasgsagdasgasgsagsdgasddgagdas',FALSE,FALSE,'djfshfgfldsjghfdslg','dfhflhfdusagsauigidhsaguishguihsgsf','Jack','Daniels','Friend','098-765-4321','yes@yes.ca','Isabella','Goldshire','Friend','444-333-2222','animal@lover.ca','PetSmart');

INSERT INTO catapplication (nameofcat,fname,lname,address,city,province,postalcode,homephone,cellphone,email,age,personcatisfor,householdagreement,membersintroduced,catallergies,howmanyadults,howmanychild,childrenages,childrenhandling,childrenvisit,visitingfrequency,childrenprepared,familybusy,activefamily,scheduleregularity,familypersonality,plans,typeofresidence,own,landlordcontact,catsallowed,restrictions,outdoorareas,busystreet,cathome,livingsituationchanges,anycats,catsinfo,catattitude,otherpets,otherpetsinfo,spayedandneutered,animallocation,prioradoption,groupname,surrenderedanimal,circumstances,vetinfo,expectations,mainpurpose,primarycaretaker,catsprior,vacationhome,leftaloneweekday,leftaloneweekend,dailyexercise,petadjustment,foodexpenses,vetexpenses,groomingexpenses,boardingexpenses,gender,catcoat,catage,breedtypecolour,friendlywithchild,friendlywithdogs,friendlywithcats,friendlywithme,friendlywithvisitors,enjoybeinggroomed,enjoybeingheld,enjoybeingpetted,becalm,beactive,beplayful,bequiet,beindependant,wakeupatnight,aggressivebehaviour,beprotective,littertrained,declawed,firsttimeowner,handledifficultcat,medicalhandling,kittenmedical,nailcare,behaviouralissues,declawcat,catpast,catinsurance,giveupcat,catcirucumstances,additionalinformation,ref1fname,ref1lname,ref1relationship,ref1phonenumber,ref1email,ref2fname,ref2lname,ref2relationship,ref2phonenumber,ref2email,findoutanimal)
VALUES ('Alphonse the 4th','Kester','Adam','123 Giddyup RD','Edmonton','AB','C1C 1C1','123-456-7890',123-456-7890,'Kester@adam.ca',18,'Myself',TRUE,TRUE,FALSE,1,0,'18','Somewhat Capable',FALSE,'Never','Understand the limits of a cat','Somewhat','Regular','Calm','No change','Home','Home',TRUE,NULL,TRUE,'Outdoor cat room','Not busy','Free Roam','sagasjlghaslgsahgahsgudlshgjsalghajslghaslkgsdshjkl','dgasfgsgfdshajhdahguislghajgjsa;gdhalg',FALSE,'Diabetic cat','No Preference',TRUE,'Bird: Yells a lot and is annoying',1,'Home in downtown',TRUE,'SPCA',TRUE,'asglhdajlghdasjlghasjkgldsahgjskg','Outgoing and fun','Emotional help','Myself',TRUE,TRUE,'Tabby',3,1,1,1,10000,11000,12000,13000,TRUE,TRUE,'adolescent','S','N','V','S','V','V','V','S','S','S','S','V','N','S','N','N','N','N','N','Y','Y',TRUE,TRUE,'Salon','Any and all are fine',FALSE,'agdasgsagdasgasgsagsdgasddgagdas',FALSE,FALSE,'djfshfgfldsjghfdslg','dfhflhfdusagsauigidhsaguishguihsgsf','Jack','Daniels','Friend','098-765-4321','yes@yes.ca','Isabella','Goldshire','Friend','444-333-2222','animal@lover.ca','PetSmart');

INSERT INTO catapplication (nameofcat,fname,lname,address,city,province,postalcode,homephone,cellphone,email,age,personcatisfor,householdagreement,membersintroduced,catallergies,howmanyadults,howmanychild,childrenages,childrenhandling,childrenvisit,visitingfrequency,childrenprepared,familybusy,activefamily,scheduleregularity,familypersonality,plans,typeofresidence,own,landlordcontact,catsallowed,restrictions,outdoorareas,busystreet,cathome,livingsituationchanges,anycats,catsinfo,catattitude,otherpets,otherpetsinfo,spayedandneutered,animallocation,prioradoption,groupname,surrenderedanimal,circumstances,vetinfo,expectations,mainpurpose,primarycaretaker,catsprior,vacationhome,leftaloneweekday,leftaloneweekend,dailyexercise,petadjustment,foodexpenses,vetexpenses,groomingexpenses,boardingexpenses,gender,catcoat,catage,breedtypecolour,friendlywithchild,friendlywithdogs,friendlywithcats,friendlywithme,friendlywithvisitors,enjoybeinggroomed,enjoybeingheld,enjoybeingpetted,becalm,beactive,beplayful,bequiet,beindependant,wakeupatnight,aggressivebehaviour,beprotective,littertrained,declawed,firsttimeowner,handledifficultcat,medicalhandling,kittenmedical,nailcare,behaviouralissues,declawcat,catpast,catinsurance,giveupcat,catcirucumstances,additionalinformation,ref1fname,ref1lname,ref1relationship,ref1phonenumber,ref1email,ref2fname,ref2lname,ref2relationship,ref2phonenumber,ref2email,findoutanimal)
VALUES ('Jack','Khadeejah','Carey','Somewhere is near','Base camp Alpha','AT','D1D 1D1','123-456-7890',123-456-7890,'Khadeejah@carey.ca',45,'Husband',TRUE,TRUE,FALSE,2,0,'45,47','Somewhat Capable',FALSE,'Never','Understand the limits of a cat','Somewhat','Regular','Calm','No change','Home','Home',TRUE,NULL,TRUE,'Outdoor cat room','Not busy','Free Roam','sagasjlghaslgsahgahsgudlshgjsalghajslghaslkgsdshjkl','dgasfgsgfdshajhdahguislghajgjsa;gdhalg',FALSE,'Diabetic cat','No Preference',TRUE,'Bird: Yells a lot and is annoying',1,'Home in downtown',TRUE,'SPCA',TRUE,'asglhdajlghdasjlghasjkgldsahgjskg','Outgoing and fun','Emotional help','Myself',TRUE,TRUE,'Tabby',3,1,1,1,10000,11000,12000,13000,TRUE,TRUE,'any','S','N','V','S','V','V','V','S','S','S','S','V','N','S','N','N','N','N','N','Y','Y',TRUE,TRUE,'Salon','Any and all are fine',FALSE,'agdasgsagdasgasgsagsdgasddgagdas',FALSE,FALSE,'djfshfgfldsjghfdslg','dfhflhfdusagsauigidhsaguishguihsgsf','Jack','Daniels','Friend','098-765-4321','yes@yes.ca','Isabella','Goldshire','Friend','444-333-2222','animal@lover.ca','PetSmart');

INSERT INTO catapplication (nameofcat,fname,lname,address,city,province,postalcode,homephone,cellphone,email,age,personcatisfor,householdagreement,membersintroduced,catallergies,howmanyadults,howmanychild,childrenages,childrenhandling,childrenvisit,visitingfrequency,childrenprepared,familybusy,activefamily,scheduleregularity,familypersonality,plans,typeofresidence,own,landlordcontact,catsallowed,restrictions,outdoorareas,busystreet,cathome,livingsituationchanges,anycats,catsinfo,catattitude,otherpets,otherpetsinfo,spayedandneutered,animallocation,prioradoption,groupname,surrenderedanimal,circumstances,vetinfo,expectations,mainpurpose,primarycaretaker,catsprior,vacationhome,leftaloneweekday,leftaloneweekend,dailyexercise,petadjustment,foodexpenses,vetexpenses,groomingexpenses,boardingexpenses,gender,catcoat,catage,breedtypecolour,friendlywithchild,friendlywithdogs,friendlywithcats,friendlywithme,friendlywithvisitors,enjoybeinggroomed,enjoybeingheld,enjoybeingpetted,becalm,beactive,beplayful,bequiet,beindependant,wakeupatnight,aggressivebehaviour,beprotective,littertrained,declawed,firsttimeowner,handledifficultcat,medicalhandling,kittenmedical,nailcare,behaviouralissues,declawcat,catpast,catinsurance,giveupcat,catcirucumstances,additionalinformation,ref1fname,ref1lname,ref1relationship,ref1phonenumber,ref1email,ref2fname,ref2lname,ref2relationship,ref2phonenumber,ref2email,findoutanimal)
VALUES ('Elmo','Savanah','Melton','Here me out','Yes','RI','E1E 1E1','123-456-7890',123-456-7890,'savanah@melton.ca',19,'Myself',TRUE,TRUE,FALSE,1,1,'12','Somewhat Capable',FALSE,'Never','Understand the limits of a cat','Somewhat','Regular','Calm','No change','Home','Home',TRUE,NULL,TRUE,'Outdoor cat room','Not busy','Free Roam','sagasjlghaslgsahgahsgudlshgjsalghajslghaslkgsdshjkl','dgasfgsgfdshajhdahguislghajgjsa;gdhalg',FALSE,'Diabetic cat','No Preference',TRUE,'Bird: Yells a lot and is annoying',1,'Home in downtown',TRUE,'SPCA',TRUE,'asglhdajlghdasjlghasjkgldsahgjskg','Outgoing and fun','Emotional help','Myself',TRUE,TRUE,'Tabby',3,1,1,1,10000,11000,12000,13000,TRUE,TRUE,'adult','S','N','V','S','V','V','V','S','S','S','S','V','N','S','N','N','N','N','N','Y','Y',TRUE,TRUE,'Salon','Any and all are fine',FALSE,'agdasgsagdasgasgsagsdgasddgagdas',FALSE,FALSE,'djfshfgfldsjghfdslg','dfhflhfdusagsauigidhsaguishguihsgsf','Jack','Daniels','Friend','098-765-4321','yes@yes.ca','Isabella','Goldshire','Friend','444-333-2222','animal@lover.ca','PetSmart');


INSERT INTO dogapplication (nameofdog,fname,lname,address,city,province,postalcode,homephone,cellphone,email,age/*clear*/,householdagreement,membersintroduced,dogallergies,howmanyadults,howmanychild,childrenages,childrenhandling,childrenvisit,visitingfrequency,childrenprepared,familybusy,activefamily,scheduleregularity,familypersonality,plans/*clear*/,typeofresidence,own,landlordcontact,dogsallowed,restrictions,livingsituationchanges,outdoorareas,fencetype,fenceheight,dogaddons/*clear*/,anydogs,dogsinfo,otherpets,spayedandneutered,animallocation,prioradoption,groupname,surrenderedanimal,circumstances,vetinfo/*clear*/,dogprimarycaretaker,dogsprior,housebroken,dogcorrection,dogstayvacation,dogstayday,dogstaynight,leftaloneweek,leftaloneweekend,petadjustment,dogactivties,foodexpenses,vetexpenses,groomingexpenses,boardingexpenses,gender,dogcoat,dogage,breedtypecolour,friendlywithchild,friendlywithdogs,friendlywithcats,friendlywithme,friendlywithvisitors,enjoybeinggroomed,enjoybeingheld,enjoybeingpetted,becalm,beactive,beplayful,bequiet,beindependant,wakeupatnight,aggressivebehaviour,beprotective,housetrained,obediencetrained,firsttimeowner,obedienceknowledge,difficultdog,trainingclasses,dogexpectations,dogmedical,dogpast,doginsurance,dogmaturing,giveupdog,dogcircumstances/*clear*/,ref1fname,ref1lname,ref1relationship,ref1phonenumber,ref1email,ref2fname,ref2lname,ref2relationship,ref2phonenumber,ref2email,findoutanimal)
VALUES ('Jackson','Raymond','Si','321 Rainbow ST','Calgary','AB','A2A 2A2','098-765-4321','098-765-4321','raymond.si@edu.sait.ca',21/*clear*/,TRUE,TRUE,FALSE,1,0,NULL,'Yes',TRUE,'Sometimes','Yes','Always','Active','Irregular','Chaotic','Hawaii'/*clear*/,'Home',TRUE,NULL,TRUE,'None','No Changes','Fenced Yard','Chain',6,NULL/*clear*/,TRUE,'Old dog',FALSE,1,'Home',TRUE,'SPCA',FALSE,NULL,NULL,/*clear*/'Myself',FALSE,FALSE,'Yes','MIL','Outside House','Inside House',12,2,1,'Running,fetch',12000,13000,14000,15000,'Either','Spotted','Young','Any','V','S','N','V','S','N','V','S','N','V','S','N','V','S','N','V','S','N','V','S','V','N','None',TRUE,NULL,TRUE,TRUE,NULL,NULL,/*48*/'Van','Tu','Dad','403-444-7777','van@tu.ca','Van','Tu','Dad','403-444-7777','van@tu.ca','PetSmart');

INSERT INTO dogapplication (nameofdog,fname,lname,address,city,province,postalcode,homephone,cellphone,email,age,householdagreement,membersintroduced,dogallergies,howmanyadults,howmanychild,childrenages,childrenhandling,childrenvisit,visitingfrequency,childrenprepared,familybusy,activefamily,scheduleregularity,familypersonality,plans,typeofresidence,own,landlordcontact,dogsallowed,restrictions,livingsituationchanges,outdoorareas,fencetype,fenceheight,dogaddons,anydogs,dogsinfo,otherpets,spayedandneutered,animallocation,prioradoption,groupname,surrenderedanimal,circumstances,vetinfo,dogprimarycaretaker,dogsprior,housebroken,dogcorrection,dogstayvacation,dogstayday,dogstaynight,leftaloneweek,leftaloneweekend,petadjustment,dogactivties,foodexpenses,vetexpenses,groomingexpenses,boardingexpenses,gender,dogcoat,dogage,breedtypecolour,friendlywithchild,friendlywithdogs,friendlywithcats,friendlywithme,friendlywithvisitors,enjoybeinggroomed,enjoybeingheld,enjoybeingpetted,becalm,beactive,beplayful,bequiet,beindependant,wakeupatnight,aggressivebehaviour,beprotective,housetrained,obediencetrained,firsttimeowner,obedienceknowledge,difficultdog,trainingclasses,dogexpectations,dogmedical,dogpast,doginsurance,dogmaturing,giveupdog,dogcircumstances,ref1fname,ref1lname,ref1relationship,ref1phonenumber,ref1email,ref2fname,ref2lname,ref2relationship,ref2phonenumber,ref2email,findoutanimal)
VALUES ('Diablo','Ivan','Pwnz','461 Mountain AV','Edmonton','AB','B2B 2B2','128-965-4567','128-965-4567','ivan.pwnz@edu.sait.ca',32/*clear*/,TRUE,TRUE,FALSE,2,2,'14,13','Yes',TRUE,'Sometimes','Yes','Always','Active','Irregular','Chaotic','Hawaii'/*clear*/,'Home',TRUE,NULL,TRUE,'None','No Changes','Fenced Yard','Chain',6,NULL/*clear*/,TRUE,'Old dog',FALSE,1,'Home',TRUE,'SPCA',FALSE,NULL,NULL,/*clear*/'Myself',FALSE,FALSE,'Yes','MIL','Outside House','Inside House',12,2,1,'Running,fetch',12000,13000,14000,15000,'Either','Spotted','Young','Any','V','S','N','V','S','N','V','S','N','V','S','N','V','S','N','V','S','N','V','S','V','N','None',TRUE,NULL,TRUE,TRUE,NULL,NULL,/*48*/'Van','Tu','Dad','403-444-7777','van@tu.ca','Van','Tu','Dad','403-444-7777','van@tu.ca','PetSmart');

INSERT INTO dogapplication (nameofdog,fname,lname,address,city,province,postalcode,homephone,cellphone,email,age,householdagreement,membersintroduced,dogallergies,howmanyadults,howmanychild,childrenages,childrenhandling,childrenvisit,visitingfrequency,childrenprepared,familybusy,activefamily,scheduleregularity,familypersonality,plans,typeofresidence,own,landlordcontact,dogsallowed,restrictions,livingsituationchanges,outdoorareas,fencetype,fenceheight,dogaddons,anydogs,dogsinfo,otherpets,spayedandneutered,animallocation,prioradoption,groupname,surrenderedanimal,circumstances,vetinfo,dogprimarycaretaker,dogsprior,housebroken,dogcorrection,dogstayvacation,dogstayday,dogstaynight,leftaloneweek,leftaloneweekend,petadjustment,dogactivties,foodexpenses,vetexpenses,groomingexpenses,boardingexpenses,gender,dogcoat,dogage,breedtypecolour,friendlywithchild,friendlywithdogs,friendlywithcats,friendlywithme,friendlywithvisitors,enjoybeinggroomed,enjoybeingheld,enjoybeingpetted,becalm,beactive,beplayful,bequiet,beindependant,wakeupatnight,aggressivebehaviour,beprotective,housetrained,obediencetrained,firsttimeowner,obedienceknowledge,difficultdog,trainingclasses,dogexpectations,dogmedical,dogpast,doginsurance,dogmaturing,giveupdog,dogcircumstances,ref1fname,ref1lname,ref1relationship,ref1phonenumber,ref1email,ref2fname,ref2lname,ref2relationship,ref2phonenumber,ref2email,findoutanimal)
VALUES ('Rex','Athena','Dodd','461 Mountain AV','Edmonton','AB','C2C 2C2','128-965-4567','128-965-4567','athena@dodd.ca',44/*clear*/,TRUE,TRUE,FALSE,2,4,'15,10,11,8','Yes',TRUE,'Sometimes','Yes','Always','Active','Irregular','Chaotic','Hawaii'/*clear*/,'Home',TRUE,NULL,TRUE,'None','No Changes','Fenced Yard','Chain',6,NULL/*clear*/,TRUE,'Old dog',FALSE,1,'Home',TRUE,'SPCA',FALSE,NULL,NULL,/*clear*/'Myself',FALSE,FALSE,'Yes','MIL','Outside House','Inside House',12,2,1,'Running,fetch',12000,13000,14000,15000,'Either','Spotted','Young','Any','V','S','N','V','S','N','V','S','N','V','S','N','V','S','N','V','S','N','V','S','V','N','None',TRUE,NULL,TRUE,TRUE,NULL,NULL,/*48*/'Van','Tu','Dad','403-444-7777','van@tu.ca','Van','Tu','Dad','403-444-7777','van@tu.ca','PetSmart');

INSERT INTO dogapplication (nameofdog,fname,lname,address,city,province,postalcode,homephone,cellphone,email,age,householdagreement,membersintroduced,dogallergies,howmanyadults,howmanychild,childrenages,childrenhandling,childrenvisit,visitingfrequency,childrenprepared,familybusy,activefamily,scheduleregularity,familypersonality,plans,typeofresidence,own,landlordcontact,dogsallowed,restrictions,livingsituationchanges,outdoorareas,fencetype,fenceheight,dogaddons,anydogs,dogsinfo,otherpets,spayedandneutered,animallocation,prioradoption,groupname,surrenderedanimal,circumstances,vetinfo,dogprimarycaretaker,dogsprior,housebroken,dogcorrection,dogstayvacation,dogstayday,dogstaynight,leftaloneweek,leftaloneweekend,petadjustment,dogactivties,foodexpenses,vetexpenses,groomingexpenses,boardingexpenses,gender,dogcoat,dogage,breedtypecolour,friendlywithchild,friendlywithdogs,friendlywithcats,friendlywithme,friendlywithvisitors,enjoybeinggroomed,enjoybeingheld,enjoybeingpetted,becalm,beactive,beplayful,bequiet,beindependant,wakeupatnight,aggressivebehaviour,beprotective,housetrained,obediencetrained,firsttimeowner,obedienceknowledge,difficultdog,trainingclasses,dogexpectations,dogmedical,dogpast,doginsurance,dogmaturing,giveupdog,dogcircumstances,ref1fname,ref1lname,ref1relationship,ref1phonenumber,ref1email,ref2fname,ref2lname,ref2relationship,ref2phonenumber,ref2email,findoutanimal)
VALUES ('David','George','Best','461 Mountain AV','Edmonton','AB','D2D 2D2','128-965-4567','128-965-4567','george@best.ca',18/*clear*/,TRUE,TRUE,FALSE,2,0,NULL,'Yes',TRUE,'Sometimes','Yes','Always','Active','Irregular','Chaotic','Hawaii'/*clear*/,'Home',TRUE,NULL,TRUE,'None','No Changes','Fenced Yard','Chain',6,NULL/*clear*/,TRUE,'Old dog',FALSE,1,'Home',TRUE,'SPCA',FALSE,NULL,NULL,/*clear*/'Myself',FALSE,FALSE,'Yes','MIL','Outside House','Inside House',12,2,1,'Running,fetch',12000,13000,14000,15000,'Either','Spotted','Young','Any','V','S','N','V','S','N','V','S','N','V','S','N','V','S','N','V','S','N','V','S','V','N','None',TRUE,NULL,TRUE,TRUE,NULL,NULL,/*48*/'Van','Tu','Dad','403-444-7777','van@tu.ca','Van','Tu','Dad','403-444-7777','van@tu.ca','PetSmart');

INSERT INTO dogapplication (nameofdog,fname,lname,address,city,province,postalcode,homephone,cellphone,email,age,householdagreement,membersintroduced,dogallergies,howmanyadults,howmanychild,childrenages,childrenhandling,childrenvisit,visitingfrequency,childrenprepared,familybusy,activefamily,scheduleregularity,familypersonality,plans,typeofresidence,own,landlordcontact,dogsallowed,restrictions,livingsituationchanges,outdoorareas,fencetype,fenceheight,dogaddons,anydogs,dogsinfo,otherpets,spayedandneutered,animallocation,prioradoption,groupname,surrenderedanimal,circumstances,vetinfo,dogprimarycaretaker,dogsprior,housebroken,dogcorrection,dogstayvacation,dogstayday,dogstaynight,leftaloneweek,leftaloneweekend,petadjustment,dogactivties,foodexpenses,vetexpenses,groomingexpenses,boardingexpenses,gender,dogcoat,dogage,breedtypecolour,friendlywithchild,friendlywithdogs,friendlywithcats,friendlywithme,friendlywithvisitors,enjoybeinggroomed,enjoybeingheld,enjoybeingpetted,becalm,beactive,beplayful,bequiet,beindependant,wakeupatnight,aggressivebehaviour,beprotective,housetrained,obediencetrained,firsttimeowner,obedienceknowledge,difficultdog,trainingclasses,dogexpectations,dogmedical,dogpast,doginsurance,dogmaturing,giveupdog,dogcircumstances,ref1fname,ref1lname,ref1relationship,ref1phonenumber,ref1email,ref2fname,ref2lname,ref2relationship,ref2phonenumber,ref2email,findoutanimal)
VALUES ('Carlos','Padraig','Ventura','461 Mountain AV','Edmonton','AB','E2E 2E2','128-965-4567','128-965-4567','padraig@ventura.ca',52/*clear*/,TRUE,TRUE,FALSE,1,0,NULL,'Yes',TRUE,'Sometimes','Yes','Always','Active','Irregular','Chaotic','Hawaii'/*clear*/,'Home',TRUE,NULL,TRUE,'None','No Changes','Fenced Yard','Chain',6,NULL/*clear*/,TRUE,'Old dog',FALSE,1,'Home',TRUE,'SPCA',FALSE,NULL,NULL,/*clear*/'Myself',FALSE,FALSE,'Yes','MIL','Outside House','Inside House',12,2,1,'Running,fetch',12000,13000,14000,15000,'Either','Spotted','Young','Any','V','S','N','V','S','N','V','S','N','V','S','N','V','S','N','V','S','N','V','S','V','N','None',TRUE,NULL,TRUE,TRUE,NULL,NULL,/*48*/'Van','Tu','Dad','403-444-7777','van@tu.ca','Van','Tu','Dad','403-444-7777','van@tu.ca','PetSmart');


INSERT INTO events (`name`,address,description,coordinator,`date`,starttime,endtime) 
VALUES ('Animal Meet and Greet','123 Main ST','Come and meet some animals','Tony Hawk','2020-04-02','9:00am','3:00pm');

INSERT INTO events (`name`,address,description,coordinator,`date`,starttime,endtime) 
VALUES ('"Baked" Sale','420 Weed St','blze it','Snoop Dogg','2020-04-20','4:20am','4:20pm');

INSERT INTO events (`name`,address,description,coordinator,`date`,starttime,endtime) 
VALUES ('Dog Adoption','123 South St','Adoption for dogs','Mark Jensen','2020-01-20','11:00am','5:00pm');

INSERT INTO events (`name`,address,description,coordinator,`date`,starttime,endtime) 
VALUES ('Dog Adoption','123 South St','Adoption for dogs','Mark Jensen','2020-02-20','11:00am','5:00pm');

INSERT INTO events (`name`,address,description,coordinator,`date`,starttime,endtime) 
VALUES ('Dog Adoption','123 South St','Adoption for dogs','Mark Jensen','2020-03-20','11:00am','5:00pm');

INSERT INTO events (`name`,address,description,coordinator,`date`,starttime,endtime) 
VALUES ('Dog Adoption','123 South St','Adoption for dogs','Mark Jensen','2020-04-20','11:00am','5:00pm');

INSERT INTO events (`name`,address,description,coordinator,`date`,starttime,endtime) 
VALUES ('Bake Sale','345 North St','Fundraiser','James','2020-04-09','10:00am','3:00pm');

INSERT INTO events (`name`,address,description,coordinator,`date`,starttime,endtime) 
VALUES ('Co-fundraiser','378 East St','Fundraiser with Health Canada','James','2020-04-15','10:00am','5:00pm');

INSERT INTO events (`name`,address,description,coordinator,`date`,starttime,endtime) 
VALUES ('Bake Sale','345 North St','Fundraiser','James','2020-04-21','10:00am','3:00pm');


INSERT INTO eventstaff (eventid, staffid) VALUES (1, 1);
INSERT INTO eventstaff (eventid, staffid) VALUES (1, 3);
INSERT INTO eventstaff (eventid, staffid) VALUES (1, 11);


INSERT INTO animals (`name`, `date`, age, species, breed, bio, medicalhistory, `status`)
VALUES('Jack', '2020-01-19', 5, 'Dog', 'Terrier', 'this is the bio field', 'this is the medical history field', 'foster care');

INSERT INTO animals (`name`, `date`, age, species, breed, bio, medicalhistory, `status`)
VALUES('Fluffy', '2020-02-21', 5, 'Dog', 'Poodle', 'this is the bio field', 'this is the medical history field', 'quarantine');

INSERT INTO animals (`name`, `date`, age, species, breed, bio, medicalhistory, `status`)
VALUES('James', '2020-03-19', 5, 'Dog', 'Mix', 'this is the bio field', 'this is the medical history field', 'quarantine');

INSERT INTO animals (`name`, `date`, age, species, breed, bio, medicalhistory, `status`)
VALUES('Royale', '2020-04-1', 5, 'Dog', 'Husky', 'this is the bio field', 'this is the medical history field', 'quarantine');

INSERT INTO animals (`name`, `date`, age, species, breed, bio, medicalhistory, `status`)
VALUES('Ode', '2020-01-10', 5, 'Dog', 'Mix', 'this is the bio field', 'this is the medical history field', 'evaluation');

INSERT INTO animals (`name`, `date`, age, species, breed, bio, medicalhistory, `status`)
VALUES('Garfield', '2020-01-05', 5, 'Cat', 'Tabby', 'this is the bio field', 'this is the medical history field', 'evaluation');

INSERT INTO animals (`name`, `date`, age, species, breed, bio, medicalhistory, `status`)
VALUES('Catters', '2020-02-11', 5, 'Cat', 'Siamese', 'this is the bio field', 'this is the medical history field', 'foster care');

INSERT INTO animals (`name`, `date`, age, species, breed, bio, medicalhistory, `status`)
VALUES('Baron', '2020-03-17', 5, 'Cat', 'Fat', 'this is the bio field', 'this is the medical history field', 'foster care');
